USE ConvStore_DB;
GO

-- Create SQL Server roles
CREATE ROLE Staff;
CREATE ROLE Manager;

-- Permissions for Staff Role (limited access)
GRANT SELECT, REFERENCES ON [User] TO Staff;
GRANT SELECT, REFERENCES ON Supplier TO Staff;
GRANT SELECT, INSERT, UPDATE, REFERENCES ON [Order] TO Staff;
GRANT SELECT, REFERENCES ON Product TO Staff;
GRANT SELECT, INSERT, UPDATE, REFERENCES ON OrderProducts TO Staff;
GRANT SELECT, REFERENCES ON Inventory TO Staff;
GRANT SELECT, INSERT, REFERENCES ON Notification TO Staff;
GRANT SELECT, REFERENCES ON Changelog TO Staff;
DENY INSERT, UPDATE, DELETE ON [User] TO Staff;
GRANT EXECUTE TO Staff;
DENY EXECUTE ON usp_AssignUserRole TO Staff;
DENY EXECUTE ON usp_AddUser TO Staff;
DENY EXECUTE ON usp_UpdateUser TO Staff;
DENY EXECUTE ON usp_DeleteUser TO Staff;

-- Permissions for Manager Role (full access)
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON [User] TO Manager;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON Supplier TO Manager;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON [Order] TO Manager;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON Product TO Manager;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON OrderProducts TO Manager;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON Inventory TO Manager;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON Notification TO Manager;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON Changelog TO Manager;
GRANT EXECUTE TO Manager;
GO